theme: jekyll-theme-minimal
font-icon: /assets/css/font-awesome-4.7.0/css/font-awesome.min.css

# 你的求职方向，比如前端开发工程师等
title: 软件测试方向

# 对你自己的简洁描述
description: 我平时喜欢听歌看书

# 你的美照地址
logo: https://imgchr.com/i/rI8M7t

# 你的名字
name: 余阳

# 你的联系方式
phone: 188888888888

# 你的邮箱
email: LeBron@unkown.com

# 你目前的住址
address: 湖南长沙

# 你毕业院校
school: 莎士比亚高中

# 你的专业
profession: 软件技术

# 你的学位
degree:大专在读

# 你获得过的证书或奖励
credential: 三届MVP/三届NBA冠军